project:
  type: website

website:
  title: "Fabiana Madrid"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: homework.qmd
        text: Homework

format:
  html:
    theme: cosmo
    toc: true